
#CC=m68k-apple-macos-gcc
#CXX=m68k-apple-macos-g++
#AR=m68k-apple-macos-ar
#RANLIB=m68k-apple-macos-ranlib
CC=powerpc-apple-macos-gcc -carbon
CXX=powerpc-apple-macos-g++ -carbon
AR=powerpc-apple-macos-ar
RANLIB=powerpc-apple-macos-ranlib

CFLAGS= -I. -I../.. -I$(HOME)/Retro68-build/toolchain/powerpc-apple-macos/include/SDL -I$(HOME)/Mesa-2.4.1/Headers -DFxU64=long -DC_USE_SDL

OBJS=$(subst .c,.o,$(wildcard *.c)) $(subst .cpp,.o,$(wildcard *.cpp))

.c.o:
	$(CXX) $(CFLAGS) -c -o $@ $<

.cpp.o:
	$(CXX) $(CFLAGS) -c -o $@ $<


all: $(OBJS)

clean:
	rm -f *.o
